"use client";
/* Logo previews are local data URLs, so framework image optimization is not applicable. */
/* eslint-disable @next/next/no-img-element */

import Link from "next/link";
import { useEffect, useRef, useState } from "react";
import type { LucideIcon } from "lucide-react";
import { Accordion, AccordionContent, AccordionItem, AccordionTrigger } from "@/components/ui/accordion";
import { Avatar, AvatarFallback } from "@/components/ui/avatar";
import { Table, TableBody, TableCaption, TableCell, TableHead, TableHeader, TableRow } from "@/components/ui/table";
import {
  ArrowLeft, ArrowRight, Bell, Building2, Check, CircleAlert,
  GraduationCap, History, Inbox,
  KeyRound, LogOut, Menu, MessageSquareText, Palette, Plus,
  Radio, Send, Settings, ShieldCheck, Sun,
  UserPlus, Users, WalletCards, X
} from "lucide-react";

type Portal = "creator" | "authority" | "member";
type CreatorView = "overview" | "people" | "authorities" | "groups" | "delivery" | "billing" | "branding";
type AuthorityView = "inbox" | "compose" | "history";
type MemberView = "inbox" | "history" | "preferences";
type Modal = "people" | "authority" | "group" | "announcement" | "branding" | null;
type ThemeMode="system"|"light"|"dark";
type BrandData={name:string;code:string;color:string;secondaryColor:string;logo:string};
type Person={id:string;name:string;email:string;phone:string;group:string};
type Group={id:string;name:string;type:string};
type Authority={id:string;personId:string;level:string;scope:string};
const demoBrand:BrandData={name:"Demo University",code:"DEMO-ORG",color:"#176b91",secondaryColor:"#d6ad43",logo:""};
const initials=(value:string)=>value.split(/\s+/).filter(Boolean).slice(0,2).map(v=>v[0]).join("").toUpperCase()||"AH";
const safeCell=(value:string)=>!/^[=+@-]/.test(value.trim());
const readableText=(hex:string)=>{const value=hex.replace("#","");if(value.length!==6)return"#ffffff";const [r,g,b]=[0,2,4].map(i=>parseInt(value.slice(i,i+2),16)/255).map(channel=>channel<=.04045?channel/12.92:Math.pow((channel+.055)/1.055,2.4));return .2126*r+.7152*g+.0722*b>.36?"#071c2d":"#ffffff"};

const roleInfo = {
  creator:{icon:Building2,label:"Organization owner",title:"Create or manage a space",help:"Manage people, authority, branding and delivery settings."},
  authority:{icon:ShieldCheck,label:"Authorized leader",title:"Publish within your scope",help:"Send announcements only to audiences assigned to you."},
  member:{icon:GraduationCap,label:"Member, staff or student",title:"Open your organization inbox",help:"Read verified announcements from your organization."},
};

function Brand({compact=false,onClick}:{compact?:boolean;onClick?:()=>void}){
  const inner=<><span className="mark-icon"><Radio size={compact?17:20}/></span>{!compact&&<span className="mark-word">Announcement <b>Hub</b></span>}</>;
  return onClick?<button className="brand-mark brand-button" onClick={onClick} aria-label="Go to Announcement Hub home">{inner}</button>:<Link href="/" className="brand-mark">{inner}</Link>;
}

function ThemeSelect({theme,setTheme,label="Appearance"}:{theme:ThemeMode;setTheme:(theme:ThemeMode)=>void;label?:string}){return <label className="theme-select"><span>{label}</span><select value={theme} onChange={e=>setTheme(e.target.value as ThemeMode)} aria-label={label}><option value="system">Device setting</option><option value="light">Light</option><option value="dark">Dark</option></select></label>}

function Welcome({onEnter,theme,setTheme}:{onEnter:(p:Portal)=>void;theme:ThemeMode;setTheme:(theme:ThemeMode)=>void}){
  const [role,setRole]=useState<Portal>("creator"); const [method,setMethod]=useState<"password"|"code">("password");
  const [identifier,setIdentifier]=useState(""); const [organizationCode,setOrganizationCode]=useState(""); const [password,setPassword]=useState(""); const [formError,setFormError]=useState("");
  const current=roleInfo[role]; const Icon=current.icon;
  const unavailable=(name:string)=>setFormError(`${name} requires a configured identity service and is not active in this local prototype.`);
  const continueWithOrganization=()=>{if(role!=="creator"&&!organizationCode.trim()){setFormError("Enter the organization code supplied by your administrator.");return}if(!identifier.trim()){setFormError("Enter your approved email, phone number or member ID.");return}if(method==="password"&&!password.trim()){setFormError("Enter your password, or choose a one-time code.");return}unavailable(method==="password"?"Password sign-in":"One-time-code sign-in")};
  return <main className="welcome-shell" data-theme={theme}><a className="skip-link" href="#access-panel">Skip to sign in</a>
    <nav className="welcome-nav"><Brand/><div className="welcome-controls"><span>Prototype access review</span><ThemeSelect theme={theme} setTheme={setTheme} label="Colour mode"/></div></nav>
    <section className="welcome-intro"><p className="eyebrow">Announcement Hub prototype</p><h1>Official messages for your organization.</h1><p>Choose a role to inspect its workflow. Production sign-in remains disabled until a verified identity service is connected.</p></section>
    <section className="entry-layout">
      <div className="role-list" aria-label="Choose your role">{(Object.keys(roleInfo) as Portal[]).map(id=>{const r=roleInfo[id],I=r.icon;return <button key={id} className={`role-row ${role===id?"active":""}`} onClick={()=>setRole(id)}><span className="role-icon"><I size={20}/></span><span><small>{r.label}</small><strong>{r.title}</strong><em>{r.help}</em></span><ArrowRight size={18}/></button>})}</div>
      <section className="access-panel" id="access-panel">
        <div className="access-heading"><span className="access-icon"><Icon size={22}/></span><div><p>{current.label}</p><h2>Sign in</h2></div></div>
        <button type="button" className="oauth-button" onClick={()=>unavailable("Google sign-in")}><span>G</span> Continue with Google</button><div className="divider"><span>or use organization access</span></div>
        {role!=="creator"&&<label><span>Organization code</span><input value={organizationCode} onChange={event=>setOrganizationCode(event.target.value)} aria-label="Organization code" autoComplete="organization"/></label>}
        <label><span>Email, phone number or member ID</span><input value={identifier} onChange={event=>setIdentifier(event.target.value)} aria-label="Email, phone number or member ID" autoComplete="username"/></label>
        {method==="password"&&<label><span>Password</span><input value={password} onChange={event=>setPassword(event.target.value)} type="password" aria-label="Password" autoComplete="current-password"/></label>}
        {formError&&<p className="inline-error" role="alert"><CircleAlert size={16}/>{formError}</p>}
        <button className="primary-action" onClick={continueWithOrganization}>{method==="password"?"Sign in":"Send one-time code"}<ArrowRight size={17}/></button>
        <button className="text-action" onClick={()=>setMethod(method==="password"?"code":"password")}><KeyRound size={15}/>{method==="password"?"Use a one-time code":"Use a password instead"}</button>
        <p className="access-note">Google access will work only after an identity provider verifies an approved organization member.</p>
        <div className="prototype-access"><p><strong>Prototype preview</strong> skips authentication and contains no real organization data.</p><button type="button" className="secondary" onClick={()=>onEnter(role)}>Preview {current.label.toLowerCase()} portal</button></div>
      </section>
    </section>
    <footer className="site-footer"><span>© {new Date().getFullYear()} Announcement Hub</span><nav><Link href="/privacy">Privacy</Link><Link href="/terms">Terms</Link></nav></footer>
  </main>;
}

const creatorNav=[
  ["overview","Overview",Inbox],["people","People",Users],["authorities","Authorities",ShieldCheck],["groups","Groups",Building2],["delivery","Delivery",MessageSquareText],["billing","Credits and billing",WalletCards],["branding","Branding",Palette]
] as const;
const authorityNav=[["inbox","Overview",Inbox],["compose","Create announcement",Send],["history","Sent history",History]] as const;
const memberNav=[["inbox","Inbox",Inbox],["history","History",History],["preferences","Preferences",Settings]] as const;

function Sidebar({portal,view,setView,onExit,mobileOpen,setMobileOpen,brand,theme,setTheme}:{portal:Portal;view:string;setView:(v:string)=>void;onExit:()=>void;mobileOpen:boolean;setMobileOpen:(v:boolean)=>void;brand:BrandData;theme:ThemeMode;setTheme:(theme:ThemeMode)=>void}){
  const items=portal==="creator"?creatorNav:portal==="authority"?authorityNav:memberNav;
  return <aside className={`sidebar ${mobileOpen?"mobile-open":""}`}><div className="sidebar-brand"><Brand compact onClick={()=>setView(items[0][0])}/><span>Announcement Hub</span><button type="button" className="mobile-close" onClick={()=>setMobileOpen(false)} aria-label="Close menu"><X size={20}/></button></div><div className="org-identity"><span className="org-avatar">{brand.logo?<img src={brand.logo} alt={`${brand.name} logo`}/>:initials(brand.name)}</span><span><strong>{brand.name}</strong><small>{brand.code}</small></span></div><nav aria-label="Workspace navigation"><p>{portal.toUpperCase()} WORKSPACE</p>{items.map(([id,label,I])=><button type="button" key={id} className={`nav-item ${view===id?"active":""}`} onClick={()=>{setView(id);setMobileOpen(false)}} aria-current={view===id?"page":undefined}><I size={18}/><span>{label}</span></button>)}</nav><div className="sidebar-bottom"><ThemeSelect theme={theme} setTheme={setTheme}/><button type="button" className="switch-button" onClick={onExit}><ArrowLeft size={17}/> Switch role</button><div className="user-row"><span>DP</span><div><strong>Demo person</strong><small>{portal==="creator"?"Space creator":portal==="authority"?"Authorized leader":"Member"}</small></div>{portal==="member"&&<button type="button" aria-label="Open preferences" onClick={()=>setView("preferences")}><Settings size={17}/></button>}</div></div></aside>;
}

function Header({title,description,onMenu,action}:{title:string;description:string;onMenu:()=>void;action?:React.ReactNode}){return <header className="page-header"><button type="button" className="mobile-menu" onClick={onMenu} aria-label="Open menu"><Menu size={21}/></button><div><p>ORGANIZATION SPACE</p><h1>{title}</h1><span>{description}</span></div>{action&&<div className="header-actions">{action}</div>}</header>}
function EmptyState({icon:Icon,title,body,action}:{icon:LucideIcon;title:string;body:string;action?:React.ReactNode}){return <section className="empty-state"><span><Icon size={24}/></span><h2>{title}</h2><p>{body}</p>{action}</section>}

function CreatorDashboard({view,setView,setModal,toast,people,groups,authorities,brand}:{view:CreatorView;setView:(v:CreatorView)=>void;setModal:(m:Modal)=>void;toast:(s:string)=>void;people:Person[];groups:Group[];authorities:Authority[];brand:BrandData}){
  if(view==="overview")return <><Header title="Overview" description="Set up the organization before inviting members" onMenu={()=>{}}/><section className="setup-card setup-tracker"><div className="setup-summary"><span>SPACE SETUP</span><h2>Complete your organization setup</h2><p>Connect real member data before activity and delivery reporting are shown.</p><div className="setup-progress"><span>1 of 4 complete</span><div role="progressbar" aria-label="Organization setup progress" aria-valuemin={0} aria-valuemax={4} aria-valuenow={1}><i/></div></div></div><Accordion type="single" defaultValue="branding" collapsible className="setup-accordion"><AccordionItem value="created" className="setup-step done"><AccordionTrigger><span className="step-number"><Check size={14}/></span><span><strong>Space created</strong><small>{brand.name}</small></span></AccordionTrigger><AccordionContent><p>Your organization space and code are ready for configuration.</p></AccordionContent></AccordionItem><AccordionItem value="branding" className="setup-step"><AccordionTrigger><span className="step-number">2</span><span><strong>Add logo and brand colors</strong><small>Make the space recognizable</small></span></AccordionTrigger><AccordionContent><p>Set the two-color palette and circular logo members will see.</p><button className="secondary" onClick={()=>setView("branding")}>Open branding</button></AccordionContent></AccordionItem><AccordionItem value="people" className="setup-step"><AccordionTrigger><span className="step-number">3</span><span><strong>Import organization members</strong><small>{people.length?`${people.length} preview records added`:"No member records connected yet"}</small></span></AccordionTrigger><AccordionContent><p>Add people individually, paste rows or upload a CSV file.</p><button className="secondary" onClick={()=>setView("people")}>Open people</button></AccordionContent></AccordionItem><AccordionItem value="authority" className="setup-step"><AccordionTrigger><span className="step-number">4</span><span><strong>Assign announcement authority</strong><small>Define who can contact each audience</small></span></AccordionTrigger><AccordionContent><p>Create groups first, then give leaders the minimum audience scope they need.</p><button className="secondary" onClick={()=>setView("authorities")}>Open authorities</button></AccordionContent></AccordionItem></Accordion></section><section className="honest-grid"><article><Users size={20}/><strong>Member activity</strong><p>Available after members join and activity tracking begins.</p></article><article><MessageSquareText size={20}/><strong>Delivery reporting</strong><p>Available after a messaging provider is connected.</p></article></section></>;
  if(view==="people")return <><Header title="People" description="Import and review organization members" onMenu={()=>{}} action={<button type="button" className="primary-action" onClick={()=>setModal("people")}><UserPlus size={17}/> Add people</button>}/>{people.length?<section className="data-panel member-directory"><div className="data-head"><div><h2>Member directory</h2><p>Preview records added during this session</p></div><span>{people.length} {people.length===1?"person":"people"}</span></div><Table><TableCaption className="sr-only">Preview organization members</TableCaption><TableHeader><TableRow><TableHead>Member</TableHead><TableHead>Contact</TableHead><TableHead>Group</TableHead><TableHead>Status</TableHead></TableRow></TableHeader><TableBody>{people.map(p=><TableRow key={p.id}><TableCell><div className="member-name"><Avatar size="sm"><AvatarFallback>{initials(p.name)}</AvatarFallback></Avatar><strong>{p.name}</strong></div></TableCell><TableCell>{p.email||p.phone}</TableCell><TableCell>{p.group||"Unassigned"}</TableCell><TableCell><span className="record-status"><Check size={13}/> Preview record</span></TableCell></TableRow>)}</TableBody></Table></section>:<EmptyState icon={Users} title="No members have been imported" body="Add one person, paste comma-separated rows, or upload a CSV. Directory sync needs a secure backend." action={<button type="button" className="primary-action" onClick={()=>setModal("people")}>Choose an input method</button>}/>}</>;
  if(view==="authorities")return <><Header title="Authorities" description="Assign hierarchy levels and audience scope" onMenu={()=>{}} action={<button type="button" className="primary-action" onClick={()=>people.length&&groups.length?setModal("authority"):toast("Add at least one person and one group first.")}><Plus size={17}/> Assign authority</button>}/>{authorities.length?<section className="data-panel"><div className="data-head"><h2>Preview assignments</h2><span>{authorities.length} total</span></div>{authorities.map(a=><div className="authority-card" key={a.id}><ShieldCheck size={19}/><div><strong>{people.find(p=>p.id===a.personId)?.name}</strong><p>{a.level} · {a.scope}</p></div></div>)}</section>:<EmptyState icon={ShieldCheck} title="No authority assignments yet" body="Import members and create groups first, then assign a hierarchy level and permitted audience."/>}</>;
  if(view==="groups")return <><Header title="Groups" description="Create departments, offices, courses and classes" onMenu={()=>{}} action={<button type="button" className="primary-action" onClick={()=>setModal("group")}><Plus size={17}/> Add group</button>}/>{groups.length?<section className="data-panel"><div className="data-head"><h2>Audience groups</h2><span>{groups.length} total</span></div>{groups.map(g=><div className="authority-card" key={g.id}><Building2 size={19}/><div><strong>{g.name}</strong><p>{g.type}</p></div></div>)}</section>:<EmptyState icon={Building2} title="No audience groups yet" body="Create a department, office, course, class or project."/>}</>;
  if(view==="delivery")return <><Header title="Delivery" description="Provider-confirmed channel outcomes" onMenu={()=>{}}/><EmptyState icon={MessageSquareText} title="No delivery records" body="Sent, delivered, read and failed statuses will appear after a messaging provider is connected and the first announcement is sent."/></>;
  if(view==="billing")return <><Header title="Credits and billing" description="Control SMS fallback spending" onMenu={()=>{}}/><section className="billing-explainer"><WalletCards size={24}/><h2>Connect an SMS provider</h2><p>Messaging credit pays the SMS gateway that sends fallback messages. It is separate from Wi-Fi service and mobile data.</p><button className="primary-action" onClick={()=>toast("Provider connection is not available in this prototype.")}>Review provider setup</button></section></>;
  return <><Header title="Branding" description="Apply your organization identity to every member experience" onMenu={()=>{}}/><section className="brand-settings"><div className="brand-preview" style={{background:brand.color,color:readableText(brand.color)}}><span className="org-avatar large">{brand.logo?<img src={brand.logo} alt={`${brand.name} logo`}/>:initials(brand.name)}</span><strong>{brand.name}</strong><small>{brand.code}</small><span className="brand-swatches" aria-label="Selected brand colors"><i style={{background:brand.color}}/><i style={{background:brand.secondaryColor}}/></span></div><div><h2>Organization appearance</h2><p>Choose a primary and secondary color plus a circular logo. The palette is applied to navigation, actions, selected states, surfaces and the workspace background across all three portals.</p><button type="button" className="primary-action" onClick={()=>setModal("branding")}><Palette size={17}/> Customize appearance</button></div></section></>;
}

function AuthorityDashboard({view,setView,notify,groups}:{view:AuthorityView;setView:(v:AuthorityView)=>void;notify:(message:string)=>void;groups:Group[]}){
  if(view==="compose")return <><Header title="Create announcement" description="Only creator-assigned audiences are available" onMenu={()=>{}}/><AudienceComposer choices={groups.map(g=>g.name)} onCancel={()=>setView("inbox")} onReview={()=>notify("Preview validated. Production sending still requires server authorization and provider review.")}/></>;
  if(view==="history")return <><Header title="Sent history" description="Announcements sent from your account" onMenu={()=>{}}/><EmptyState icon={History} title="No announcements sent" body="Your sent announcements and verified delivery outcomes will appear here."/></>;
  return <><Header title="Authority overview" description="Your publishing access is limited to assigned audiences" onMenu={()=>{}} action={<button type="button" className="primary-action" onClick={()=>groups.length?setView("compose"):notify("Create a group in the owner portal before composing.")}><Plus size={17}/> Create announcement</button>}/><section className="scope-card"><ShieldCheck size={22}/><div><span>PREVIEW SCOPE</span><h2>{groups.length?groups.map(g=>g.name).join(", "):"No audience assigned"}</h2><p>The production server must re-check permission scope for every send. Hiding options in the interface is not sufficient authorization.</p></div></section><EmptyState icon={Inbox} title="No drafts or recent sends" body="Create a group in the owner portal to test scoped selection."/></>;
}

function MemberDashboard({view,theme,setTheme}:{view:MemberView;theme:ThemeMode;setTheme:(theme:ThemeMode)=>void}){
  if(view==="preferences")return <><Header title="Preferences" description="Choose appearance and notification channels" onMenu={()=>{}}/><section className="preference-list"><label><span><Sun size={19}/><strong>Appearance</strong></span><select aria-label="Appearance" value={theme} onChange={e=>setTheme(e.target.value as ThemeMode)}><option value="system">Use device setting</option><option value="light">Light</option><option value="dark">Dark</option></select></label><label><span><Bell size={19}/><strong>Notifications</strong></span><select aria-label="Notification channel"><option>In-app, WhatsApp and SMS fallback</option><option>In-app and SMS fallback</option><option>In-app only</option></select></label></section></>;
  if(view==="history")return <><Header title="Announcement history" description="Previously read and archived messages" onMenu={()=>{}}/><EmptyState icon={History} title="No announcement history" body="Announcements you read or archive will appear here with the sender, department, date and time."/></>;
  return <><Header title="Inbox" description="Official announcements from your organization" onMenu={()=>{}}/><EmptyState icon={Inbox} title="No announcements" body="New authorized announcements will appear here with the sender, group, date, time and priority."/></>;
}

function AudienceComposer({onCancel,onReview,choices}:{onCancel:()=>void;onReview:()=>void;choices:string[]}){const [message,setMessage]=useState("");const [selected,setSelected]=useState<string[]>([]);
  return <section className="composer-page"><label><span>Audience within your authority</span><div className="audience-options">{choices.map(c=><button key={c} className={selected.includes(c)?"selected":""} onClick={()=>setSelected(selected.includes(c)?selected.filter(x=>x!==c):[...selected,c])}>{selected.includes(c)&&<Check size={14}/>} {c}</button>)}</div></label><label><span>Announcement</span><textarea value={message} onChange={e=>setMessage(e.target.value)} aria-label="Announcement message"/></label><div className="cost-note"><CircleAlert size={18}/><p>Recipient count and SMS estimate will appear after real member data and a messaging provider are connected.</p></div><footer><button className="secondary" onClick={onCancel}>Cancel</button><button className="primary-action" disabled={!message.trim()||!selected.length} onClick={onReview}><Send size={16}/> Review announcement</button></footer></section>;
}

function ActionModal({type,close,commit,people,groups,brand,error}:{type:Exclude<Modal,null>;close:()=>void;commit:(value:Person|Group|Authority|BrandData|Person[])=>void;people:Person[];groups:Group[];brand:BrandData;error:(s:string)=>void}){
  const ref=useRef<HTMLElement>(null),[method,setMethod]=useState("individual"),[name,setName]=useState(""),[email,setEmail]=useState(""),[phone,setPhone]=useState(""),[group,setGroup]=useState(""),[raw,setRaw]=useState(""),[kind,setKind]=useState("Department"),[personId,setPersonId]=useState(people[0]?.id||""),[level,setLevel]=useState("Department head"),[scope,setScope]=useState(groups[0]?.name||""),[draft,setDraft]=useState(brand),[message,setMessage]=useState("");
  useEffect(()=>{const old=document.activeElement as HTMLElement|null,dialog=ref.current;dialog?.querySelector<HTMLElement>("button,input,select,textarea")?.focus();const key=(e:KeyboardEvent)=>{if(e.key==="Escape")close();if(e.key==="Tab"&&dialog){const items=[...dialog.querySelectorAll<HTMLElement>('button:not([disabled]),input:not([disabled]),select:not([disabled]),textarea:not([disabled])')];if(!items.length)return;const first=items[0],last=items.at(-1);if(e.shiftKey&&document.activeElement===first){e.preventDefault();last?.focus()}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first.focus()}}};document.addEventListener("keydown",key);return()=>{document.removeEventListener("keydown",key);old?.focus()}},[close]);
  const fail=(s:string)=>{setMessage(s);error(s)}, parse=()=>raw.split(/\r?\n/).filter(Boolean).map((line,i)=>{const [n="",e="",p="",g=""]=line.split(",").map(v=>v.trim());if(!n||(!e&&!p)||![n,e,p,g].every(safeCell))throw Error(`Row ${i+1} needs a name, email or phone, and safe text.`);return{id:crypto.randomUUID(),name:n,email:e,phone:p,group:g}});
  const chooseFile=async(e:React.ChangeEvent<HTMLInputElement>)=>{const f=e.target.files?.[0];if(!f)return;if(!f.name.toLowerCase().endsWith(".csv")||f.size>1048576)return fail("Use a CSV file no larger than 1 MB.");setRaw(await f.text())};
  const chooseLogo=(e:React.ChangeEvent<HTMLInputElement>)=>{const f=e.target.files?.[0];if(!f)return;if(!["image/png","image/jpeg","image/svg+xml"].includes(f.type)||f.size>1048576)return fail("Use a PNG, JPEG or SVG no larger than 1 MB.");const r=new FileReader();r.onload=()=>setDraft({...draft,logo:String(r.result)});r.readAsDataURL(f)};
  const submit=()=>{try{if(type==="people"){if(method==="directory")return fail("Directory sync needs administrator consent and a secure backend; it cannot be simulated locally.");if(method==="individual"){if(!name||(!email&&!phone)||![name,email,phone,group].every(safeCell))return fail("Enter a safe name and either email or phone.");commit({id:crypto.randomUUID(),name,email,phone,group})}else{if(!raw.trim())return fail("Add at least one comma-separated row.");commit(parse())}}else if(type==="group"){if(!name||!safeCell(name))return fail("Enter a safe group name.");commit({id:crypto.randomUUID(),name,type:kind})}else if(type==="authority"){if(!personId||!scope)return fail("Choose a member and audience.");commit({id:crypto.randomUUID(),personId,level,scope})}else{if(!draft.name||!draft.code||![draft.color,draft.secondaryColor].every(value=>/^#[0-9a-f]{6}$/i.test(value)))return fail("Name, code and two valid colors are required.");commit(draft)}close()}catch(e){fail(e instanceof Error?e.message:"The input could not be processed.")}};
  const title={people:"Add people",authority:"Assign authority",group:"Add group",announcement:"Create announcement",branding:"Customize appearance"}[type];
  return <div className="modal-backdrop" onMouseDown={close}><section ref={ref} className="composer" role="dialog" aria-modal="true" aria-labelledby="modal-title" onMouseDown={e=>e.stopPropagation()}><header><div><p>ORGANIZATION SETUP</p><h2 id="modal-title">{title}</h2></div><button type="button" className="close-button" onClick={close} aria-label="Close dialog"><X size={20}/></button></header>
  {type==="people"&&<><div className="method-tabs">{[["individual","One person"],["csv","CSV file"],["paste","Paste rows"],["directory","Directory"]].map(([id,label])=><button type="button" key={id} className={method===id?"active":""} onClick={()=>setMethod(id)}>{label}</button>)}</div>{method==="individual"&&<div className="form-grid"><label><span>Full name *</span><input value={name} onChange={e=>setName(e.target.value)}/></label><label><span>Email</span><input type="email" value={email} onChange={e=>setEmail(e.target.value)}/></label><label><span>Phone</span><input type="tel" value={phone} onChange={e=>setPhone(e.target.value)}/></label><label><span>Group</span><input value={group} onChange={e=>setGroup(e.target.value)}/></label></div>}{method==="csv"&&<label><span>CSV file *</span><input type="file" accept=".csv,text/csv" onChange={chooseFile}/><small>Maximum 1 MB. Columns: name, email, phone, group.</small></label>}{method==="paste"&&<label><span>Comma-separated rows *</span><textarea value={raw} onChange={e=>setRaw(e.target.value)} placeholder="Full name, email, phone, group"/></label>}{method==="directory"&&<p className="modal-explainer">Google Workspace and Microsoft Entra connections require administrator consent, least-privilege permissions, secure server credentials, sync logs and deprovisioning.</p>}</>}
  {type==="group"&&<div className="form-grid"><label><span>Group name *</span><input value={name} onChange={e=>setName(e.target.value)}/></label><label><span>Type</span><select value={kind} onChange={e=>setKind(e.target.value)}><option>Department</option><option>Office</option><option>Course</option><option>Class</option><option>Project</option></select></label></div>}
  {type==="authority"&&<div className="form-grid"><label><span>Member</span><select value={personId} onChange={e=>setPersonId(e.target.value)}>{people.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select></label><label><span>Level</span><select value={level} onChange={e=>setLevel(e.target.value)}><option>Executive</option><option>Department head</option><option>Manager</option><option>Lecturer</option></select></label><label><span>Permitted audience</span><select value={scope} onChange={e=>setScope(e.target.value)}>{groups.map(g=><option key={g.id}>{g.name}</option>)}</select></label></div>}
  {type==="branding"&&<><p className="modal-explainer">Primary color controls navigation and key actions. Secondary color controls selected states and highlights. Both tint the full workspace while keeping text readable.</p><div className="form-grid"><label><span>Organization name *</span><input value={draft.name} onChange={e=>setDraft({...draft,name:e.target.value})}/></label><label><span>Organization code *</span><input value={draft.code} onChange={e=>setDraft({...draft,code:e.target.value.toUpperCase()})}/></label><label><span>Primary color *</span><span className="color-field"><input type="color" value={draft.color} onChange={e=>setDraft({...draft,color:e.target.value})}/><output>{draft.color.toUpperCase()}</output></span></label><label><span>Secondary color *</span><span className="color-field"><input type="color" value={draft.secondaryColor} onChange={e=>setDraft({...draft,secondaryColor:e.target.value})}/><output>{draft.secondaryColor.toUpperCase()}</output></span></label><label className="logo-field"><span>Circular logo</span><input type="file" accept="image/png,image/jpeg,image/svg+xml" onChange={chooseLogo}/><small>PNG, JPEG or SVG, maximum 1 MB. Square images crop best.</small></label></div></>}{message&&<p className="inline-error" role="alert"><CircleAlert size={16}/>{message}</p>}<footer><button type="button" className="secondary" onClick={close}>Cancel</button><button type="button" className="primary-action" onClick={submit}>Apply brand</button></footer></section></div>}

function Workspace({portal,onExit,brand,setBrand,people,setPeople,groups,setGroups,authorities,setAuthorities,theme,setTheme}:{portal:Portal;onExit:()=>void;brand:BrandData;setBrand:(b:BrandData)=>void;people:Person[];setPeople:React.Dispatch<React.SetStateAction<Person[]>>;groups:Group[];setGroups:React.Dispatch<React.SetStateAction<Group[]>>;authorities:Authority[];setAuthorities:React.Dispatch<React.SetStateAction<Authority[]>>;theme:ThemeMode;setTheme:(theme:ThemeMode)=>void}){const [creatorView,setCreatorView]=useState<CreatorView>("overview"),[authorityView,setAuthorityView]=useState<AuthorityView>("inbox"),[memberView,setMemberView]=useState<MemberView>("inbox"),[mobileOpen,setMobileOpen]=useState(false),[modal,setModal]=useState<Modal>(null),[notice,setNotice]=useState<{type:"success"|"error";text:string}|null>(null);const view=portal==="creator"?creatorView:portal==="authority"?authorityView:memberView;const setView=(next:string)=>{if(portal==="creator")setCreatorView(next as CreatorView);else if(portal==="authority")setAuthorityView(next as AuthorityView);else setMemberView(next as MemberView)};const notify=(type:"success"|"error",text:string)=>{setNotice({type,text});window.setTimeout(()=>setNotice(null),4000)};const commit=(value:Person|Group|Authority|BrandData|Person[])=>{if(Array.isArray(value)){setPeople(p=>[...p,...value]);return notify("success",`${value.length} preview members added.`)}if("email" in value){setPeople(p=>[...p,value]);return notify("success","Preview member added.")}if("personId" in value){setAuthorities(a=>[...a,value]);return notify("success","Preview authority assigned.")}if("type" in value){setGroups(g=>[...g,value]);return notify("success","Preview group added.")}setBrand(value);notify("success","Brand colors applied throughout all three portals.")};
  const brandStyle={"--org-primary":brand.color,"--org-secondary":brand.secondaryColor,"--org-on-primary":readableText(brand.color),"--org-on-secondary":readableText(brand.secondaryColor)} as React.CSSProperties;
  return <main className="app-shell" data-theme={theme} style={brandStyle}><a className="skip-link" href="#workspace-content">Skip to content</a><button type="button" className="mobile-fab" onClick={()=>setMobileOpen(true)} aria-label="Open navigation"><Menu size={20}/></button><Sidebar portal={portal} view={view} setView={setView} onExit={onExit} mobileOpen={mobileOpen} setMobileOpen={setMobileOpen} brand={brand} theme={theme} setTheme={setTheme}/>{mobileOpen&&<button type="button" className="menu-backdrop" onClick={()=>setMobileOpen(false)} aria-label="Close navigation"/>}<section className="content-shell" id="workspace-content">{portal==="creator"?<CreatorDashboard view={creatorView} setView={setCreatorView} setModal={setModal} toast={s=>notify("error",s)} people={people} groups={groups} authorities={authorities} brand={brand}/>:portal==="authority"?<AuthorityDashboard view={authorityView} setView={setAuthorityView} notify={message=>notify("success",message)} groups={groups}/>:<MemberDashboard view={memberView} theme={theme} setTheme={setTheme}/>}<footer className="workspace-footer"><Link href="/privacy">Privacy</Link><Link href="/terms">Terms</Link><button type="button" onClick={onExit}><LogOut size={15}/> Sign out of preview</button></footer></section>{modal&&<ActionModal type={modal} close={()=>setModal(null)} commit={commit} people={people} groups={groups} brand={brand} error={s=>notify("error",s)}/>} {notice&&<div className={`toast ${notice.type}`} role={notice.type==="error"?"alert":"status"}>{notice.type==="success"?<Check size={18}/>:<CircleAlert size={18}/>}<span>{notice.text}</span><button type="button" onClick={()=>setNotice(null)} aria-label="Dismiss"><X size={15}/></button></div>}</main>}

export default function Home(){const [portal,setPortal]=useState<Portal|null>(null),[brand,setBrand]=useState<BrandData>(demoBrand),[theme,setThemeState]=useState<ThemeMode>("system"),[people,setPeople]=useState<Person[]>([]),[groups,setGroups]=useState<Group[]>([]),[authorities,setAuthorities]=useState<Authority[]>([]);useEffect(()=>{const saved=window.localStorage.getItem("announcement-hub-theme");if(saved!=="light"&&saved!=="dark")return;const timer=window.setTimeout(()=>setThemeState(saved),0);return()=>window.clearTimeout(timer)},[]);const setTheme=(value:ThemeMode)=>{setThemeState(value);window.localStorage.setItem("announcement-hub-theme",value)};return portal?<Workspace portal={portal} onExit={()=>setPortal(null)} brand={brand} setBrand={setBrand} people={people} setPeople={setPeople} groups={groups} setGroups={setGroups} authorities={authorities} setAuthorities={setAuthorities} theme={theme} setTheme={setTheme}/>:<Welcome onEnter={setPortal} theme={theme} setTheme={setTheme}/>}
