"use client";

import { useMemo, useState } from "react";
import { ArrowRight, BellRing, Building2, Check, ChevronDown, Clock3, GraduationCap, KeyRound, Megaphone, MessageSquareText, MoreHorizontal, Plus, Radio, Search, Send, ShieldCheck, Smartphone, Sparkles, Users, WalletCards, X } from "lucide-react";

type Portal = "creator" | "authority" | "member";

const announcements = [
  { tag:"All staff", title:"Quarterly town hall — venue update", body:"Tomorrow’s town hall will now take place at the Main Auditorium. Please arrive by 9:45 AM.", author:"Office of the Vice Chancellor", time:"18 min ago", delivery:"1,284 reached", sms:"126 by SMS", tone:"purple" },
  { tag:"Computer Science · Level 300", title:"Database Systems lecture moved online", body:"Today’s 2:00 PM lecture will be held online. The meeting link is available in your course portal.", author:"Dr. Naa Mensah", time:"1 hr ago", delivery:"186 reached", sms:"31 by SMS", tone:"blue" },
  { tag:"Finance Office", title:"September payroll documents", body:"Department administrators should submit outstanding payroll documents before 4:00 PM Friday.", author:"Finance Directorate", time:"Yesterday", delivery:"42 reached", sms:"4 by SMS", tone:"amber" },
];

const portals = [
  { id:"creator" as Portal, icon:Building2, eyebrow:"ORGANIZATION OWNER", title:"Create or manage a space", description:"Set up your organization, verify members, control branding and assign announcement authority.", action:"Open creator portal" },
  { id:"authority" as Portal, icon:ShieldCheck, eyebrow:"AUTHORIZED LEADER", title:"Publish official updates", description:"Send announcements to the groups and departments you have permission to reach.", action:"Open authority portal" },
  { id:"member" as Portal, icon:GraduationCap, eyebrow:"MEMBER · STAFF · STUDENT", title:"Enter your organization", description:"Read verified updates in one place and receive critical notices by SMS when you are offline.", action:"Open member portal" },
];

function Mark({ compact=false }:{ compact?:boolean }) {
  return <div className="brand-mark" aria-label="Announcement Hub"><span className="mark-icon"><Radio size={compact?18:22} strokeWidth={2.4}/></span>{!compact&&<span className="mark-word">Announcement<span>Hub</span></span>}</div>;
}

function Welcome({ onEnter }:{ onEnter:(portal:Portal)=>void }) {
  const [selected,setSelected]=useState<Portal|null>(null);
  return <main className="welcome-shell">
    <nav className="welcome-nav"><Mark/><button className="text-button">How it works <ArrowRight size={15}/></button></nav>
    <section className="welcome-copy"><div className="research-pill"><Sparkles size={15}/> Built from real organizational research</div><h1>One trusted place.<br/><em>Every person reached.</em></h1><p>Official announcements for your whole organization—with automatic SMS delivery when members are offline.</p></section>
    <section className="portal-grid" aria-label="Choose how to continue">{portals.map(p=>{const Icon=p.icon;const active=selected===p.id;return <button className={`portal-card ${active?"active":""}`} key={p.id} onClick={()=>setSelected(p.id)} onDoubleClick={()=>onEnter(p.id)}><span className="portal-top"><span className="portal-icon"><Icon size={21}/></span><span className="portal-arrow"><ArrowRight size={18}/></span></span><span className="portal-eyebrow">{p.eyebrow}</span><strong>{p.title}</strong><span className="portal-description">{p.description}</span><span className="portal-action">{active?"Continue":p.action} <ArrowRight size={15}/></span></button>})}</section>
    {selected&&<section className="access-panel"><div><span className="access-kicker">SECURE ACCESS</span><strong>{selected==="creator"?"Create a new space or sign in":"Enter your organization code"}</strong></div><div className="access-form"><label><span>{selected==="creator"?"Work email or phone":"Organization code"}</span><input defaultValue={selected==="creator"?"":"PU-LEGON-24"} placeholder={selected==="creator"?"you@organization.com":"e.g. PU-LEGON-24"}/></label><button onClick={()=>onEnter(selected)}>Continue securely <ArrowRight size={17}/></button></div><p><KeyRound size={14}/> First-time access details are sent to your verified email or phone.</p></section>}
    <footer className="welcome-footer"><span><ShieldCheck size={15}/> Verified membership</span><span><Smartphone size={15}/> Offline SMS fallback</span><span><Users size={15}/> Role-based authority</span></footer>
  </main>;
}

function Workspace({ portal,onExit }:{ portal:Portal;onExit:()=>void }) {
  const [composer,setComposer]=useState(false),[sent,setSent]=useState(false),[audience,setAudience]=useState("Everyone in the organization"),[message,setMessage]=useState("");
  const estimatedSms=useMemo(()=>audience.startsWith("Everyone")?126:audience.startsWith("Computer")?31:18,[audience]);
  const send=()=>{if(!message.trim())return;setSent(true);setComposer(false);setMessage("");window.setTimeout(()=>setSent(false),3800)};
  return <main className="app-shell">
    <aside className="sidebar"><div className="sidebar-brand"><Mark compact/><span>Announcement Hub</span></div><div className="org-card"><span className="org-avatar">PU</span><span><strong>Pentecost University</strong><small>PU-LEGON-24</small></span><ChevronDown size={15}/></div><nav><button className="nav-item active"><Megaphone size={18}/> Announcements <span>8</span></button><button className="nav-item"><Users size={18}/> People</button><button className="nav-item"><ShieldCheck size={18}/> Authorities</button><button className="nav-item"><Building2 size={18}/> Departments</button><p>DELIVERY</p><button className="nav-item"><MessageSquareText size={18}/> SMS delivery</button><button className="nav-item"><WalletCards size={18}/> Credits & billing</button></nav><div className="sidebar-bottom"><button className="nav-item" onClick={onExit}><ArrowRight className="rotate" size={18}/> Switch portal</button><div className="user-row"><span>JB</span><div><strong>Joseph Bortey</strong><small>{portal==="creator"?"Space creator":portal}</small></div><MoreHorizontal size={17}/></div></div></aside>
    <section className="content-shell"><header className="app-header"><div><p>THURSDAY, 17 SEPTEMBER</p><h1>Good afternoon, Joseph.</h1></div><div className="header-actions"><button className="icon-button" aria-label="Search"><Search size={19}/></button><button className="icon-button" aria-label="Notifications"><BellRing size={19}/><i/></button><button className="compose-button" onClick={()=>setComposer(true)}><Plus size={18}/> New announcement</button></div></header>
      <section className="pulse-grid"><article className="pulse-card primary-card"><div className="card-label"><Radio size={16}/> LIVE DELIVERY PULSE</div><strong className="big-number">1,284</strong><span className="big-label">members reached today</span><div className="delivery-bar"><span style={{width:"90%"}}/></div><div className="delivery-legend"><span><i className="online"/> 1,158 in-app</span><span><i className="sms"/> 126 SMS</span><b>99.2%</b></div></article><article className="pulse-card metric-card"><span className="metric-icon purple"><Users size={20}/></span><div><small>ACTIVE MEMBERS</small><strong>1,420</strong><p><b>+38</b> this month</p></div></article><article className="pulse-card metric-card"><span className="metric-icon amber"><WalletCards size={20}/></span><div><small>SMS BALANCE</small><strong>GH₵ 284.60</strong><p>≈ 1,423 messages</p></div><button>Top up</button></article></section>
      <section className="main-grid"><div className="feed-column"><div className="section-heading"><div><h2>Recent announcements</h2><p>Official updates across your organization</p></div><button>View all <ArrowRight size={15}/></button></div><div className="announcement-list">{announcements.map(item=><article className="announcement" key={item.title}><div className={`announcement-mark ${item.tone}`}><Megaphone size={18}/></div><div className="announcement-body"><span className={`tag ${item.tone}`}>{item.tag}</span><h3>{item.title}</h3><p>{item.body}</p><div className="announcement-meta"><span>{item.author}</span><i/><span><Clock3 size={13}/> {item.time}</span><span className="delivery-stat"><Check size={13}/> {item.delivery}</span><span><MessageSquareText size={13}/> {item.sms}</span></div></div><button className="more-button" aria-label="More actions"><MoreHorizontal size={18}/></button></article>)}</div></div>
        <aside className="insights-column"><article className="insight-card"><div className="section-heading compact"><div><h2>Audience health</h2><p>Last 30 days</p></div><button><MoreHorizontal size={18}/></button></div><div className="donut-wrap"><div className="donut"><span><strong>94%</strong><small>reachable</small></span></div></div><ul className="health-list"><li><span><i className="online"/>App notifications</span><b>1,312</b></li><li><span><i className="sms"/>SMS fallback</span><b>108</b></li><li><span><i className="unverified"/>Needs verification</span><b>22</b></li></ul></article><article className="insight-card authority-card"><div className="authority-icon"><ShieldCheck size={22}/></div><div><h3>Authority requests</h3><p>3 leaders are waiting for publishing access.</p><button>Review requests <ArrowRight size={14}/></button></div><span>3</span></article></aside></section>
    </section>
    {composer&&<div className="modal-backdrop" role="presentation" onMouseDown={()=>setComposer(false)}><section className="composer" role="dialog" aria-modal="true" aria-labelledby="composer-title" onMouseDown={e=>e.stopPropagation()}><header><div><span>NEW OFFICIAL UPDATE</span><h2 id="composer-title">Create announcement</h2></div><button onClick={()=>setComposer(false)} aria-label="Close"><X size={20}/></button></header><label><span>Audience</span><select value={audience} onChange={e=>setAudience(e.target.value)}><option>Everyone in the organization</option><option>Computer Science · Level 300</option><option>Department heads</option><option>Finance Office</option></select></label><label><span>Announcement</span><textarea value={message} onChange={e=>setMessage(e.target.value)} placeholder="Write a clear, official announcement…" autoFocus/></label><div className="sms-estimate"><span><MessageSquareText size={18}/></span><div><strong>Estimated SMS fallback</strong><p>{estimatedSms} offline members × GH₵0.20</p></div><b>GH₵ {(estimatedSms*.2).toFixed(2)}</b></div><div className="composer-actions"><button className="secondary" onClick={()=>setComposer(false)}>Save draft</button><button className="send" disabled={!message.trim()} onClick={send}><Send size={16}/> Send announcement</button></div></section></div>}
    {sent&&<div className="toast"><span><Check size={16}/></span><div><strong>Announcement sent</strong><p>Online members notified; SMS fallback is in progress.</p></div></div>}
  </main>;
}

export default function Home(){const [workspace,setWorkspace]=useState(false),[portal,setPortal]=useState<Portal>("creator");const enter=(p:Portal)=>{setPortal(p);setWorkspace(true)};return workspace?<Workspace portal={portal} onExit={()=>setWorkspace(false)}/>:<Welcome onEnter={enter}/>}
